// Puude nimekiri. Muuda siin: nimed, tunnused, mida koguda.
// images: võtmed viitavad failidele kaustas images/<võti>.jpg (build.py paneb need HTML-i sisse).
const TREES = [
  {
    id: "mand", nr: 1, name: "Harilik mänd", latin: "Pinus sylvestris", group: "okaspuu",
    parts: [{ key: "oks", label: "oks" }, { key: "kabi", label: "käbi" }],
    images: [{ src: "mand_oks", caption: "Oks okaste ja noore käbiga" }, { src: "mand_kabi", caption: "Valminud käbid" }],
    tunnused: [
      "Okkad on paarikaupa (kaks okast ühes kimbus), 4–7 cm pikad, sinakasrohelised ja kergelt keerdus.",
      "Koor tüve ülaosas oranžikaspunane ja koorub õhukeste plaatidena.",
      "Käbi 3–7 cm, munajas, hallikaspruun; valmib alles teisel aastal.",
    ],
    segi: "Kuusega: kuusel on okkad üksikult, männil kahekaupa kimbus.",
    kasvab: "Liivased nõmmed, rabad, kuivad männikud. Vajab palju valgust.",
  },
  {
    id: "kuusk", nr: 2, name: "Harilik kuusk", latin: "Picea abies", group: "okaspuu", kasutamine: true,
    parts: [{ key: "oks", label: "oks" }, { key: "kabi", label: "käbi" }],
    images: [{ src: "kuusk_oks", caption: "Oks okastega" }, { src: "kuusk_kabi", caption: "Rippuvad käbid" }],
    tunnused: [
      "Okkad üksikult, lühikesed (1–2,5 cm), neljakandilised ja teravad.",
      "Okas kinnitub oksale väikese pulgakese abil – kui okkad ära pudenevad, jääb oks krobeliseks.",
      "Käbi pikk (10–16 cm), ripub oksa küljes allapoole ja kukub maha tervena.",
      "Võra on kuhikjas, alumised oksad ulatuvad tihti maani.",
    ],
    segi: "Nuluga: nulul on okkad lamedad ja pehmed, käbid seisavad oksal püsti ja pudenevad puu otsas laiali.",
    kasvab: "Niisked ja viljakad mullad, kuusikud ja segametsad. Talub varju.",
    kasutus: [
      "Ehituspuit ja saematerjal – üks tähtsamaid puiduliike Eestis.",
      "Paber ja papp (tselluloos).",
      "Jõulupuu.",
      "Muusikariistade kõlalauad (viiul, kitarr, klaver) – kuusepuit kannab heli hästi edasi.",
      "Vaik ja noored võrsed (kuusevõrsesiirup, tee).",
    ],
  },
  {
    id: "kadakas", nr: 3, name: "Harilik kadakas", latin: "Juniperus communis", group: "okaspuu",
    parts: [{ key: "oks", label: "oks" }, { key: "marikabi", label: "marikäbi" }],
    images: [{ src: "kadakas_oks", caption: "Oks torkivate okastega" }, { src: "kadakas_mari", caption: "Marikäbid, valmides sinakasmustad" }],
    tunnused: [
      "Tavaliselt põõsas või väike sammaskujuline puu.",
      "Okkad kolmekaupa männases, teravad ja torkivad, pealmisel küljel valge triip.",
      "Marikäbid ümarad: esimesel aastal rohelised, valmides (2.–3. aastal) sinakasmustad ja valge kirmega.",
    ],
    segi: "Noore kuusega: kadaka okkad on männastes kolmekaupa ja palju torkivamad.",
    kasvab: "Loopealsed, karjamaad, rannikualad, Lääne-Eesti ja saared. Vajab valgust.",
  },
  {
    id: "pihlakas", nr: 4, name: "Harilik pihlakas", latin: "Sorbus aucuparia", group: "lehtpuu", kasutamine: true,
    parts: [{ key: "leht", label: "leht" }, { key: "mari", label: "marjakobar" }],
    images: [{ src: "pihlakas_leht", caption: "Sulgjas liitleht" }, { src: "pihlakas_mari", caption: "Marjakobar" }],
    tunnused: [
      "Leht on paaritusulgjas liitleht: 9–17 lehekest, tipus üks üksik.",
      "Lehekesed piklikud, saagja servaga, alt hallikad.",
      "Lehed asetsevad oksal vaheldumisi (mitte paarikaupa vastakuti).",
      "Marjad erkoranžid või punased, tihedates kobarates; valmivad augustis-septembris.",
      "Koor sile ja hall, pungad karvased.",
    ],
    segi: "Saarega: ka saarel on sulgjas liitleht, aga saare lehed ja oksad on vastakuti ja pungad mustad.",
    kasvab: "Metsaservad, aiad, teeääred – üks tavalisemaid puid, ka linnas.",
    kasutus: [
      "Marjadest tehakse moosi, mahla, veini ja tarretist (pärast esimest külma on marjad vähem mõrud).",
      "Marjad on talvel lindudele oluline toit (siidisabad, rästad).",
      "Ilupuu aedades ja parkides.",
      "Sitke puit sobib tööriistavarteks ja treitöödeks.",
      "Rahvapärimuses kaitsepuu – pihlakaoks pandi maja kaitseks ukse kohale.",
    ],
  },
  {
    id: "tamm", nr: 5, name: "Harilik tamm", latin: "Quercus robur", group: "lehtpuu",
    parts: [{ key: "leht", label: "leht" }, { key: "toru", label: "tõru" }],
    images: [{ src: "tamm_leht", caption: "Hõlmised lehed" }, { src: "tamm_toru", caption: "Tõru kübarakesega" }],
    tunnused: [
      "Leht sügavalt hõlmine, hõlmad ümarad (mitte teravad), 5–7 paari.",
      "Leheroots väga lühike (alla 1 cm), lehe alus kõrvakujuline.",
      "Tõru istub pikal varrel (2–8 cm), kübarake katab umbes kolmandiku tõrust.",
      "Koor paks ja sügavalt lõhestunud, võra lai.",
    ],
    segi: "Kivitammega (parkides): kivitammel on pikk leheroots ja tõru ilma varreta.",
    kasvab: "Viljakad mullad, puisniidud, pargid, tammikud. Kasvab aeglaselt ja elab sadu aastaid.",
  },
  {
    id: "saar", nr: 6, name: "Harilik saar", latin: "Fraxinus excelsior", group: "lehtpuu",
    parts: [{ key: "leht", label: "leht" }, { key: "vili", label: "vili" }],
    images: [{ src: "saar_leht", caption: "Sulgjas liitleht" }, { src: "saar_vili", caption: "Tiibviljade kobar" }],
    tunnused: [
      "Paaritusulgjas liitleht 7–13 lehekesega; lehekesed piklikud, peensaagjad, ilma rootsuta.",
      "Lehed ja oksad on vastakuti (paarikaupa).",
      "Pungad on mustad ja sametised – kõige kindlam tunnus!",
      "Vili on tiibvili (pähklike koos pika tiivaga), kobarates, püsib puul talveni.",
      "Lehed tulevad kevadel kõige hiljem ja langevad sügisel roheliselt.",
    ],
    segi: "Pihlakaga: pihlaka lehed on vaheldumisi ja viljad on punased marjad.",
    kasvab: "Viljakad niisked mullad, jõelammid, pargid. Viimastel aastatel on paljud saared saaresurma tõttu haiged.",
  },
  {
    id: "vaher", nr: 7, name: "Harilik vaher", latin: "Acer platanoides", group: "lehtpuu",
    parts: [{ key: "leht", label: "leht" }, { key: "vili", label: "vili" }],
    images: [{ src: "vaher_leht", caption: "Sõrmhõlmine leht" }, { src: "vaher_vili", caption: "Tiibvili ehk „helikopter“" }],
    tunnused: [
      "Leht sõrmhõlmine 5–7 hõlmaga, iga hõlm lõpeb pika terava tipuga.",
      "Lehed on vastakuti, leheroots pikk.",
      "Murtud leherootsust tuleb piimjat mahla.",
      "Vili on kaheks jagunev tiibvili; tiivad hoiavad peaaegu sirgelt laiali (180°).",
      "Sügisel värvuvad lehed kollaseks ja oranžiks.",
    ],
    segi: "Mägivahtraga (parkides): mägivahtra hõlmad on tömbimad ja serv saagjas, tiivad hoiavad täisnurga all.",
    kasvab: "Pargid, alleed, viljakad salumetsad, ka linnatänavatel.",
  },
  {
    id: "haab", nr: 8, name: "Haab ja pappel", latin: "Populus tremula, Populus spp.", group: "lehtpuu",
    parts: [{ key: "haab", label: "haava leht" }, { key: "pappel", label: "papli leht" }],
    images: [{ src: "haab_leht", caption: "Haava leht – peaaegu ümar" }, { src: "pappel_leht", caption: "Papli lehed – munajad, alt heledad" }],
    tunnused: [
      "Haab: leht peaaegu ümar, serv jämedalt ja tömbilt sakiline.",
      "Haab: leheroots on pikk ja külgedelt lapik – seepärast värisevad lehed vähimagi tuulega.",
      "Haab: koor sile, rohekashall.",
      "Pappel (nt palsamipappel): leht munajas terava tipuga, serv peensaagjas, pealt tumeroheline, alt valkjas.",
      "Pappel: pungad kleepuvad ja lõhnavad tugevalt, koor vanematel puudel lõheline.",
    ],
    segi: "Haab ja pappel omavahel – veereta rootsu sõrmede vahel: haaval on see lapik. Papli leht on terava tipuga ja alt hele.",
    kasvab: "Haab: metsaservad, raiesmikud, kasvab kiiresti. Pappel: alleed, pargid, linnad.",
  },
  {
    id: "parn", nr: 9, name: "Harilik pärn", latin: "Tilia cordata", group: "lehtpuu", kasutamine: true,
    parts: [{ key: "leht", label: "leht" }, { key: "vili", label: "vili" }],
    images: [{ src: "parn_leht", caption: "Südajas leht" }, { src: "parn_vili", caption: "Viljakobar keeljas kandelehega" }],
    tunnused: [
      "Leht südajas, viltuse alusega ja terava tipuga, 3–8 cm, serv peensaagjas.",
      "Lehe alumisel küljel on roodude nurkades punakaspruunid karvatutid.",
      "Viljad väikesed (u 5 mm) ümarad pähklikesed kobaras; kobara küljes on pikk keeljas kandeleht, mis toimib tiivana.",
      "Õitseb juuli alguses, õied lõhnavad magusalt ja sumisevad mesilastest.",
    ],
    segi: "Suurelehise pärnaga: sellel on lehed suuremad ja alt valkjad karvatutid.",
    kasvab: "Pargid, alleed, salumetsad. Talub varju ja linnaõhku.",
    kasutus: [
      "Pärnaõietee – vana rahvaravim külmetuse vastu.",
      "Tähtis meetaim: pärnamesi.",
      "Niin (kooreseesmine kiud) – sellest tehti viiske, köisi, matte ja kotte.",
      "Pehme ja ühtlane puit sobib nikerdamiseks, puunõudeks ja mänguasjadeks.",
      "Pärnasüsi on kunstnike joonistussüsi.",
      "Populaarne allee- ja pargipuu.",
    ],
  },
  {
    id: "jalakas", nr: 10, name: "Harilik jalakas", latin: "Ulmus glabra", group: "lehtpuu",
    parts: [{ key: "leht", label: "leht" }],
    images: [{ src: "jalakas_leht", caption: "Suur kare leht, ebasümmeetriline alus" }],
    tunnused: [
      "Leht suur (8–16 cm), ovaalne, tipp järsult terav; suurtel lehtedel võib olla kolm tippu.",
      "Lehe alus on tugevasti ebasümmeetriline – üks pool ulatub üle rootsu.",
      "Serv kahekordselt saagjas (suurte sakkide peal väiksemad sakid).",
      "Lehe pealmine külg on kare nagu liivapaber, roots väga lühike.",
      "Vili on ümar lame tiibvili, seeme keskel; valmib juba mai-juunis.",
    ],
    segi: "Künnapuuga: künnapuu leht on siledam, roots pikem ja seeme asub tiiva servas.",
    kasvab: "Salumetsad, jõeorud, pangad, pargid.",
  },
  {
    id: "lepp", nr: 11, name: "Hall lepp", latin: "Alnus incana", group: "lehtpuu",
    parts: [{ key: "leht", label: "leht" }, { key: "kabi", label: "käbi" }],
    images: [{ src: "lepp_leht", caption: "Munajad terava tipuga lehed" }, { src: "lepp_kabi", caption: "Puitunud väikesed käbid" }],
    tunnused: [
      "Leht munajas terava tipuga, serv kahekordselt saagjas.",
      "Lehe alumine külg on hallikas ja karvane; lehed ei ole kunagi kleepuvad.",
      "Koor sile ja helehall.",
      "Väikesed puitunud käbid (1–1,5 cm) püsivad puul aasta läbi – ainus lehtpuu käbidega!",
    ],
    segi: "Sanglepaga: sanglepal on lehe tipp tömp või isegi nõgus, noored lehed kleepuvad ja koor tume ning lõheline.",
    kasvab: "Kraavikaldad, võsastuvad põllud, jõeääred. Kiirekasvuline pioneerpuu.",
  },
  {
    id: "toomingas", nr: 12, name: "Harilik toomingas", latin: "Prunus padus", group: "lehtpuu",
    parts: [{ key: "leht", label: "leht" }],
    images: [{ src: "toomingas_leht", caption: "Elliptilised peensaagjad lehed" }],
    tunnused: [
      "Leht elliptiline, terava tipuga, serv peensaagjas, pealt matt ja kergelt kortsuline.",
      "Leherootsu tipus, lehelaba juures on kaks väikest näärmekest (näpsakut).",
      "Murtud oks ja koor lõhnavad mõrkjalt (mandlilõhn).",
      "Kevadel valged lõhnavad õiekobarad, sügisel mustad marjad kobaras.",
    ],
    segi: "Paakspuuga: paakspuu lehe serv on terve (ilma sakkideta).",
    kasvab: "Niisked metsad, jõe- ja ojakaldad, kraaviääred, aiad.",
  },
  {
    id: "sarapuu", nr: 13, name: "Harilik sarapuu", latin: "Corylus avellana", group: "lehtpuu",
    parts: [{ key: "leht", label: "leht" }, { key: "vili", label: "pähkel" }],
    images: [{ src: "sarapuu_leht", caption: "Lai ümar leht, äkiline terav tipp" }, { src: "sarapuu_vili", caption: "Pähklid rohelises ümbrises" }],
    tunnused: [
      "Suur põõsas mitme tüvega.",
      "Leht lai, ümar või südajas, äkiliselt terava tipuga, serv kahekordselt saagjas.",
      "Leht on mõlemalt poolt pehmekarvane.",
      "Vili on pähkel rohelise sakilise ümbrise sees, 1–4 kaupa koos.",
      "Varakevadel ripuvad okstel pikad kollased urvad.",
    ],
    segi: "Halli lepaga (sarapuu leht on ümaram ja karvane) ja jalakaga (jalaka alus on viltu).",
    kasvab: "Salumetsade alusmets, viljakad mullad, metsaservad.",
  },
  {
    id: "kask", nr: 14, name: "Kask", latin: "Betula pendula, B. pubescens", group: "lehtpuu", kasutamine: true,
    parts: [{ key: "leht", label: "leht" }, { key: "vili", label: "vili (urb)" }],
    images: [{ src: "kask_leht", caption: "Kolmnurkjad-rombjad lehed" }, { src: "kask_vili", caption: "Viljaurvad lehtede vahel" }],
    tunnused: [
      "Leht kolmnurkjas või rombjas, pika terava tipuga, serv kahekordselt saagjas, roots pikk ja peenike.",
      "Koor valge ja paberjas, vanadel puudel alt must ja lõheline.",
      "Arukasel ripuvad noored oksad allapoole ja on näsalised; sookasel on oksad karvased ja leht ümaram.",
      "Vili: väikesed tiivulised pähklikesed, mis pudenevad sügisel pruunidest urbadest.",
    ],
    segi: "Halli lepaga: lepal on käbid ja leht ei ole pika terava tipuga.",
    kasvab: "Kõikjal – metsad, raiesmikud, sood, teeääred. Valgusnõudlik pioneerpuu ja Eesti rahvuspuu.",
    kasutus: [
      "Kasemahl kevadel.",
      "Saunavihad.",
      "Üks parimaid küttepuid.",
      "Vineer, mööbel, parkett, suusad, puulusikad.",
      "Kasetoht: tõrv, tohust käsitöö (märsid, karbid), tuletegemine.",
      "Must pässik (chaga) ja kasepungad rahvameditsiinis; kasesuhkur ehk ksülitool.",
    ],
  },
  {
    id: "jugapuu", nr: 15, name: "Harilik jugapuu", latin: "Taxus baccata", group: "okaspuu",
    parts: [{ key: "oks", label: "väike oksake" }],
    images: [{ src: "jugapuu_oks", caption: "Lamedad okkad ja punased seemnerüüd" }],
    tunnused: [
      "Okkad lamedad ja pehmed (ei torgi), 2–3 cm, pealt tumeroheline läikiv, alt heledam.",
      "Okkad asetsevad oksa külgedel kahes reas nagu kammi piid.",
      "Käbi asemel on punane mahlane seemnerüü, mille sees on üks seeme.",
      "TÄHELEPANU: okkad, seemned ja puit on mürgised – ära pane suhu ja pese pärast käsi.",
    ],
    segi: "Kuuse või nuluga: nende okkad on kõvemad ja neil on käbid.",
    kasvab: "Pargid, kalmistud, hekid. Looduslikult vaid Lääne-Eesti saartel, kus ta on looduskaitse all – korja väike oksake ainult aiast või pargist.",
  },
];

// Sildile kirjutatav info (koolist antud nõue)
const LABEL_FIELDS = [
  { key: "koht", label: "Koht, kust korjatud", placeholder: "nt Nõmme, Männiku tee kooli kõrval" },
  { key: "korjaja", label: "Kes korjas", placeholder: "nimi" },
  { key: "kuupaev", label: "Kuupäev", type: "date" },
];
